# Generated by Django 4.0.2 on 2022-03-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eartag', models.IntegerField()),
                ('DOB', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('breed', models.CharField(max_length=30)),
                ('stage', models.CharField(max_length=20)),
                ('calvings', models.IntegerField(default=0)),
                ('heat', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dailydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('eartag', models.IntegerField()),
                ('totalmilk', models.IntegerField()),
                ('production', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('conf_pass', models.CharField(max_length=30)),
            ],
        ),
    ]
