# Generated by Django 4.0.1 on 2022-02-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eartag', models.IntegerField()),
                ('DOB', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('breed', models.CharField(max_length=30)),
                ('stage', models.CharField(max_length=20)),
                ('calvings', models.IntegerField()),
            ],
        ),
    ]
