# Generated by Django 4.0.2 on 2022-03-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_animaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('eartag', models.IntegerField()),
                ('totalmilk', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='animaldata',
            name='calvings',
            field=models.IntegerField(default=0),
        ),
    ]
