# Generated by Django 4.0.2 on 2022-03-13 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_dailydata_alter_animaldata_calvings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='production',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
