# Generated by Django 4.0.2 on 2022-03-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_animaldata_heat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heatdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('eartag', models.IntegerField()),
                ('breed', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='dailydata',
            name='calvings',
            field=models.IntegerField(default=0),
        ),
    ]
