# Generated by Django 4.0.2 on 2022-03-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_heatdata_dailydata_calvings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalmilk', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
