# Generated by Django 4.0.2 on 2022-03-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_milk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('totalmilk', models.IntegerField()),
                ('Earnings_bulls', models.IntegerField()),
                ('Earnings_extra', models.IntegerField()),
                ('Expenditure_Feeder', models.IntegerField()),
                ('Expenditure_Medical', models.IntegerField()),
                ('Expenditure_Labour', models.IntegerField()),
                ('Expenditure_Eexpenses', models.IntegerField()),
            ],
        ),
    ]
